### ISSUE TITLE
Input escribiendo

### ISSUE THREAD

**Issue by tavi004** [Inevio/UIKit#1]
El color del texto escribiendo no tiene que ser tan clarito, tiene que ser #545f65
![google chrome - main html - screen shot 16 dic 2015 13 45 50](https://cloud.githubusercontent.com/assets/3248361/11841148/7dfa21f8-a3fb-11e5-8754-960d2bb0273f.png)

**Comment by tavi004** [comment]
El height del input normal tiene que ser de 30px con borde incluido

**Comment by tavi004** [comment]
El texto tendría que estar 1px mas abajo

**Comment by tavi004** [comment]
El color del placeholder tendría que ser #889399

**Comment by tavi004** [comment]
Pasa algo raro y se corta el inner shadow cuando está active

![adobe photoshop cc 2015 - ui kit psd 980- regular input rgb-8 - - screen shot 16 dic 2015 13 53 14](https://cloud.githubusercontent.com/assets/3248361/11841266/6014d498-a3fc-11e5-977d-b6383d9fff01.png)

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/UIKit/commit/96cd537b6b63fcc1422b78681b16e7a7b7e4749f
