### ISSUE TITLE
Input grande 

### ISSUE THREAD

**Issue by tavi004** [Inevio/UIKit#2]
<strong>Input Normal</strong>
-2px mas pequeño de height y width
-2px mas grande la barrita de después del icono de search
-Bajar el texto 1px y cambiar el color a #889399

<strong>Input Active</strong>
-2px mas pequeño de height y width
-2px mas grande la barrita de después del icono de search
-Bajar el texto 1px
-No se tiene el inner shadow

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/UIKit/commit/a08643344fd705e53e3d33a47e87b92781440b93

**Comment by tavi004** [comment]
NOPE, de cerrado nada bonito!

El placeholder no está cambiado a #889399
Hay que mover el icono de search y la barra 1px a la izq, pero el texto que se quedé donde está, cuidado.

![image](https://cloud.githubusercontent.com/assets/3248361/11975756/5786e65c-a971-11e5-88f0-1dddb77a8792.png)

**Comment by Navas23** [comment]
Fixed https://github.com/Inevio/UIKit/commit/42a2faa1c1cfec9591e9bcae18e13e09942aba79
