### ISSUE TITLE
El color del placeholder está to mal premoh

### ISSUE THREAD

**Issue by tavi004** [Inevio/UIKit#8]
![img_2016-01-13 16 42 52](https://cloud.githubusercontent.com/assets/3248361/12298906/b8ce7ade-ba14-11e5-98d9-b1bba9ac13d9.jpg)

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/UIKit/commit/7890008eb0def80d6cc8142dedccace4f4142753
